version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  test:
    docker:
      - image: "node:12.16.1"
      - image: "circleci/mongo:4.2"
    steps:
      - checkout
      - run:
          name: Install node modules
          command: npm i
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Codecov
          command: "bash <(curl -s https://codecov.io/bash)"
workflows:
  build-and-test:
    jobs:
      - test
